- name: Admin configure users prerequesites
  hosts: localhost

  tasks:
    # - name: Check if admin is authenticated with OpenShift 4
    #   ansible.builtin.command: oc whoami
    #   register: oc_whoami_result
    #   changed_when: false
    #   ignore_errors: true
    #   no_log: true

    # - name: Fail if not connected on cluster
    #   ansible.builtin.fail:
    #     msg: "You are not logged into the cluster. Please use 'oc login' and re-run this playbook"
    #   when: oc_whoami_result.rc != 0

    # - name: Fail if not logged in as admin
    #   ansible.builtin.fail:
    #     msg: "You are logged in but you are not 'admin' user. Please log in with user 'admin'"
    #   when: oc_whoami_result.stdout != "admin" or oc_whoami_result.stdout != "system:admin"

    - name: Ensure users namespace exists
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "namespace-user{{ item }}"
      register: namespaceusers
      until: namespaceusers is succeeded
      retries: 60
      delay: 10
      failed_when: namespaceusers is failed or namespaceusers.failed
      with_sequence: start=1 end={{ num_users }}

    - name: Grant cluster-admin role to users in their namespaces
      kubernetes.core.k8s:
        state: present
        namespace: "namespace-user{{ item }}"
        kind: RoleBinding
        api_version: rbac.authorization.k8s.io/v1
        name: user-cluster-admin-binding
        definition:
          kind: RoleBinding
          apiVersion: rbac.authorization.k8s.io/v1
          metadata:
            name: user-cluster-admin-binding
            namespace: "namespace-user{{ item }}"
          subjects:
            - kind: User
              name: "user{{ item }}"
              apiGroup: rbac.authorization.k8s.io
          roleRef:
            kind: ClusterRole
            name: cluster-admin
            apiGroup: rbac.authorization.k8s.io
      register: rbacusers
      until: rbacusers is succeeded
      retries: 60
      delay: 10
      failed_when: rbacusers is failed or rbacusers.failed
      with_sequence: start=1 end={{ num_users }}

    - name: Moving openshift-monitoring pods to run on control-planes
      kubernetes.core.k8s:
        state: present
        template: "configmap-monitoring.yaml.j2"
      register: cmmonit
      until: cmmonit is succeeded
      retries: 60
      delay: 10
      failed_when: cmmonit is failed or cmmonit.failed

    - name: Adding default tolerations and nodeselector on openshift-gitops
      kubernetes.core.k8s:
        kind: Namespace
        name: "{{ item }}"
        merge_type: merge
        resource_definition:
          metadata:
            annotations:
              scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator": "Exists"}]'
              openshift.io/node-selector: "node-role.kubernetes.io/master=\"\""
      register: tolerations
      until: tolerations is succeeded
      retries: 60
      delay: 10
      failed_when: tolerations is failed or tolerations.failed
      loop:
        - openshift-storage
        - openshift-cnv

    - name: Moving pods on openshift-cnv to masters
      kubernetes.core.k8s:
        api_version: hco.kubevirt.io/v1beta1
        kind: HyperConverged
        name: kubevirt-hyperconverged
        merge_type: merge
        namespace: openshift-cnv
        resource_definition:
          spec:
            infra:
              nodePlacement:
                nodeSelector:
                  node-role.kubernetes.io/infra: ""
              tolerations:
                - operator: Exists
      register: cnvinfra
      until: cnvinfra is succeeded
      retries: 60
      delay: 10
      failed_when: cnvinfra is failed or cnvinfra.failed

    - name: Add tolerations to run csidrivers on masters
      kubernetes.core.k8s:
        kind: ConfigMap
        name: rook-ceph-operator-config
        merge_type: merge
        namespace: openshift-storage
        resource_definition:
          data:
            CSI_PLUGIN_TOLERATIONS: |
              - operator: Exists
      register: csistorage
      until: csistorage is succeeded
      retries: 60
      delay: 10
      failed_when: csistorage is failed or csistorage.failed

    - name: Delete applicationset on openshift-gitops
      kubernetes.core.k8s:
        api_version: v1
        kind: Pod
        namespace: openshift-gitops
        state: absent
      register: appsetrm
      until: appsetrm is succeeded
      retries: 60
      delay: 10
      failed_when: appsetrm is failed or appsetrm.failed

    - name: Delete all pods in the namespaces
      kubernetes.core.k8s:
        api_version: v1
        kind: Pod
        namespace: "{{ item }}"
        state: absent
        label_selectors: ""
      loop:
        - openshift-gitops
      register: deletepods
      until: deletepods is succeeded
      retries: 60
      delay: 10
      failed_when: deletepods is failed or deletepods.failed

    - name: Getting all nodes
      kubernetes.core.k8s_info:
        kind: Node
      register: allnodes

    - name: Getting only worker nodes
      ansible.builtin.set_fact:
        nodes_list: "{{ allnodes.resources | selectattr('metadata.labels', 'defined') | \
                     selectattr('metadata.labels', 'search', 'node-role.kubernetes.io/worker') | map(attribute='metadata.name') | list }}"

    - name: Getting only control-planes
      ansible.builtin.set_fact:
        controlplane_nodes_list: "{{ allnodes.resources | selectattr('metadata.labels', 'defined') | \
                     selectattr('metadata.labels', 'search', 'node-role.kubernetes.io/control-plane') | map(attribute='metadata.name') | list }}"

    - name: Add label node-role.kubernetes.io/infra to all master nodes
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Node
          metadata:
            name: "{{ item }}"
            labels:
              node-role.kubernetes.io/infra: ""
      loop: "{{ controlplane_nodes_list }}"

    - name: Add label userX=true to all worker nodes
      ansible.builtin.command:
        cmd: oc label node "{{ nodes_list[item | int  % nodes_list | length - 1 ] }}" user{{ item | int }}="true"
      with_sequence: start=1 end={{ num_users }}

    - name: New /etc/bashrc file
      ansible.builtin.template:
        src: bashrc-bastion.j2
        dest: "/etc/bashrc"
        mode: '0644'
      become: true
      become_method: sudo

    - name: Clone tmux repo to lab-user
      ansible.builtin.git:
        repo: https://github.com/lgchiaretto/tmux.git
        dest: /home/lab-user/tmux
      ignore_errors: true

    - name: Execute configure-local.sh script
      ansible.builtin.shell:
        cmd: /home/lab-user/tmux/configure-local.sh
      ignore_errors: true

    - name: Create configure-tmux-users.sh script
      ansible.builtin.template:
        src: 'configure-tmux-users.sh.j2'
        dest: '/home/lab-user/configure-tmux-users.sh'
        mode: '0755'
      ignore_errors: true

    - name: Execute configure-tmux-users.sh script
      ansible.builtin.shell:
        cmd: /home/lab-user/configure-tmux-users.sh
      become: true
      become_method: sudo
      ignore_errors: true

    - name: Clone tmux plugins repo to users
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm.git
        dest: /home/user{{ item | int }}/.tmux/plugins/tpm
      with_sequence: start=1 end={{ num_users }}
      become: true
      become_method: sudo
      ignore_errors: true

    - name: Copy configure-tmux-users.sh to all users
      ansible.builtin.shell:
        cmd: '/home/lab-user/configure-tmux-users.sh'
      ignore_errors: true

    - name: Changing the file ocp-cluster.tmux
      ansible.builtin.replace:
        path: /home/user{{ item | int }}/.tmux/ocp-cluster.tmux
        regexp: '/tmp/dummy-file-tmux'
        replace: '~/.dummy-file-tmux'
      with_sequence: start=1 end={{ num_users }}
      become: true
      become_method: sudo
      ignore_errors: true

    - name: Create the ClusterRole to user view server info
      kubernetes.core.k8s:
        kind: ClusterRole
        namespace: 'namespace-user{{ item | int }}'
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRole
          metadata:
            name: view-server-version
          rules:
            - apiGroups: ["config.openshift.io"]
              resources: ["clusterversions"]
              verbs: ["get"]
      with_sequence: start=1 end={{ num_users }}
      ignore_errors: true

    - name: Create the ClusterRoleBinding to user view server info
      kubernetes.core.k8s:
        kind: ClusterRoleBinding
        namespace: 'namespace-user{{ item | int }}'
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: view-server-version-binding
          subjects:
            - kind: User
              name: 'user{{ item | int }}'
              apiGroup: rbac.authorization.k8s.io
          roleRef:
            kind: ClusterRole
            name: view-server-version
            apiGroup: rbac.authorization.k8s.io
      with_sequence: start=1 end={{ num_users }}
      ignore_errors: true

    - name: Ensure community.crypto is installed
      ansible.builtin.command:
        cmd: ansible-galaxy collection install community.crypto
      register: install_result

    - name: Ensure .ssh directory exists on users dir
      ansible.builtin.file:
        path: /home/user{{ item }}/.ssh
        state: directory
        owner: 'user{{ item }}'
        group: 'user{{ item }}'
        mode: '0700'
      with_sequence: start=1 end={{ num_users }}
      become: true
      become_method: ansible.builtin.sudo

    - name: Generate RSA 2048 SSH key pair for users
      community.crypto.openssh_keypair:
        path: /home/user{{ item }}/.ssh/id_rsa
        type: rsa
        size: 2048
        state: present
        mode: '0600'
        owner: 'user{{ item }}'
        group: 'user{{ item }}'
      register: ssh_key_result
      with_sequence: start=1 end={{ num_users }}
      become: true
      become_method: ansible.builtin.sudo

    # - name: Ensure openshift-nmstate exists
    #   kubernetes.core.k8s:
    #     state: present
    #     definition:
    #       apiVersion: v1
    #       kind: Namespace
    #       metadata:
    #         name: openshift-nmstate
    #   register: namespacenmstate
    #   retries: 60
    #   delay: 10
    #   ignore_errors: true

    # - name: Create the nmstate operator group
    #   kubernetes.core.k8s:
    #     kind: OperatorGroup
    #     definition:
    #       apiVersion: operators.coreos.com/v1
    #       kind: OperatorGroup
    #       metadata:
    #         annotations:
    #           olm.providedAPIs: NMState.v1.nmstate.io
    #         name: openshift-nmstate-flnnw
    #         namespace: openshift-nmstate
    #       spec:
    #         targetNamespaces:
    #           - openshift-nmstate
    #         upgradeStrategy: Default
    #   ignore_errors: true

    # - name: Create the nmstate subscription
    #   kubernetes.core.k8s:
    #     kind: Subscription
    #     definition:
    #       apiVersion: operators.coreos.com/v1alpha1
    #       kind: Subscription
    #       metadata:
    #         labels:
    #           operators.coreos.com/kubernetes-nmstate-operator.openshift-nmstate: ""
    #         name: kubernetes-nmstate-operator
    #         namespace: openshift-nmstate
    #       spec:
    #         channel: stable
    #         installPlanApproval: Automatic
    #         name: kubernetes-nmstate-operator
    #         source: redhat-operators
    #         sourceNamespace: openshift-marketplace
    #   ignore_errors: true

    # - name: Pause for 20 seconds to wait for pods
    #   ansible.builtin.pause:
    #     seconds: 20

    # - name: Wait for all pods to be running on openshift-nmstate
    #   kubernetes.core.k8s_info:
    #     api_version: v1
    #     kind: Pod
    #     namespace: "openshift-nmstate"
    #   register: pod_list
    #   until: pod_list.resources | selectattr('status.phase', 'eq', 'Running') | list | length == pod_list.resources | length
    #   retries: 60
    #   delay: 10
    #   ignore_errors: true

    # - name: Create the nmstate
    #   kubernetes.core.k8s:
    #     kind: NMState
    #     definition:
    #       apiVersion: nmstate.io/v1
    #       kind: NMState
    #       metadata:
    #         name: nmstate
    #       spec: {}
    #   ignore_errors: true

    # - name: Pause for 20 seconds to create nmstate CRD
    #   ansible.builtin.pause:
    #     seconds: 20

    # - name: Configuring NMState NNCP
    #   kubernetes.core.k8s:
    #     kind: NodeNetworkConfigurationPolicy
    #     definition:
    #       apiVersion: nmstate.io/v1
    #       kind: NodeNetworkConfigurationPolicy
    #       metadata:
    #         name: br-ex-network
    #       spec:
    #         nodeSelector:
    #           node-role.kubernetes.io/worker: ''
    #         desiredState:
    #           ovn:
    #             bridge-mappings:
    #               - localnet: br-ex-network
    #                 bridge: br-ex
    #                 state: present
    #   ignore_errors: true

    - name: Remove argocd CRD on openshift-gitops
      kubernetes.core.k8s:
        kind: ArgoCD
        api_version: argoproj.io/v1alpha1
        namespace: openshift-gitops
        name: openshift-gitops
        state: absent
      register: removeargo
      ignore_errors: true

    - name: Get all applications on openshift-gitops
      kubernetes.core.k8s_info:
        kind: Application
        api_version: argoproj.io/v1alpha1
        namespace: openshift-gitops
      register: application_crds
      ignore_errors: true

    - name: Remove applications
      kubernetes.core.k8s:
        kind: Application
        api_version: argoproj.io/v1alpha1
        namespace: openshift-gitops
        name: "{{ item.metadata.name }}"
        state: absent
      loop: "{{ application_crds.resources }}"
      ignore_errors: true

    - name: Remover finalizer of the applications
      kubernetes.core.k8s:
        kind: Application
        api_version: argoproj.io/v1alpha1
        namespace: openshift-gitops
        definition:
          metadata:
            name: "{{ item.metadata.name }}"
            finalizers: "{{ item.metadata.finalizers | difference(['resources-finalizer.argocd.argoproj.io']) }}"
      loop: "{{ application_crds.resources }}"
      when: "'resources-finalizer.argocd.argoproj.io' in item.metadata.finalizers"
      ignore_errors: true

    - name: Removing OADP projects
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "oadp-user{{ item }}"
      register: removeoadp
      until: removeoadp is succeeded
      retries: 60
      delay: 10
      failed_when: removeoadp is failed or removeoadp.failed
      with_sequence: start=1 end={{ num_users }}
      ignore_errors: true

    - name: Remover a assinatura do operador OpenShift GitOps
      kubernetes.core.k8s:
        api_version: operators.coreos.com/v1alpha1
        namespace: openshift-operators
        kind: Subscription
        name: openshift-gitops-operator
        state: absent
      ignore_errors: true

    - name: Remover o ClusterServiceVersion associado ao operador OpenShift GitOps
      kubernetes.core.k8s:
        api_version: operators.coreos.com/v1alpha1
        namespace: openshift-operators
        kind: clusterserviceversion
        name: openshift-gitops-operator.v1.13.3
        state: absent
      ignore_errors: true