- name: Preparing  exercise11
  hosts: localhost
  gather_facts: true

  vars:
    user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Removing VM A
      kubernetes.core.k8s:
        state: absent
        template: "exercise11-create-vm-a.yaml.j2"
      register: deletevma
      until: deletevma is succeeded
      retries: 60
      delay: 10
      failed_when: deletevma is failed or deletevma.failed

    - name: Removing VM B
      kubernetes.core.k8s:
        state: absent
        template: "exercise11-create-vm-b.yaml.j2"
      register: deletevmb
      until: deletevmb is succeeded
      retries: 60
      delay: 10
      failed_when: deletevma is failed or deletevma.failed

    - name: Wait for the Virtual Machine A to be removed
      kubernetes.core.k8s_info:
        kind: VirtualMachine
        namespace: "namespace-{{ user }}"
        name: "exercise11-a"
      register: cleanvma
      retries: 60
      delay: 2
      until: cleanvma.resources | length == 0

    - name: Wait for the Virtual Machine B to be removed
      kubernetes.core.k8s_info:
        kind: VirtualMachine
        namespace: "namespace-{{ user }}"
        name: "exercise11-b"
      register: cleanvmb
      retries: 60
      delay: 2
      until: cleanvmb.resources | length == 0

    - name: Removing NAD
      kubernetes.core.k8s:
        state: absent
        template: "exercise11-create-nad.yaml.j2"
      register: deletenad
      until: deletenad is succeeded
      retries: 60
      delay: 10
      failed_when: deletenad is failed or deletenad.failed

    - name: Removing the idrsa secret
      kubernetes.core.k8s:
        state: absent
        template: "exercise8-secret.yaml.j2"
      register: secretidrsa
      until: secretidrsa is succeeded
      retries: 60
      delay: 10
      failed_when: secretidrsa is failed or secretidrsa.failed

    - name: Creating NAD
      kubernetes.core.k8s:
        state: present
        template: "exercise11-create-nad.yaml.j2"
      register: createnad
      until: createnad is succeeded
      retries: 60
      delay: 10
      failed_when: createnad is failed or createnad.failed

    - name: Get user SSH key
      ansible.builtin.slurp:
        src: "/home/{{ user }}/.ssh/id_rsa.pub"
      register: usersshkey

    - name: Create the idrsa secret
      kubernetes.core.k8s:
        state: present
        template: "exercise11-secret.yaml.j2"
      register: secretidrsa
      until: secretidrsa is succeeded
      retries: 60
      delay: 10
      failed_when: secretidrsa is failed or secretidrsa.failed

    - name: Creating VM A
      kubernetes.core.k8s:
        state: present
        template: "exercise11-create-vm-a.yaml.j2"
      register: createvma
      until: createvma is succeeded
      retries: 60
      delay: 10
      failed_when: createvma is failed or createvma.failed

    - name: Creating VM B
      kubernetes.core.k8s:
        state: present
        template: "exercise11-create-vm-b.yaml.j2"
      register: createvmb
      until: createvmb is succeeded
      retries: 60
      delay: 10
      failed_when: createvmb is failed or createvmb.failed

    - name: Wait for VM A to be running
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        namespace: "namespace-{{ user }}"
        name: "exercise11-a"
      register: exercise11ainfo
      until: " exercise11ainfo.resources | length > 0 and exercise11ainfo.resources[0].status.phase == 'Running'"
      retries: 60
      delay: 10
      failed_when: exercise11ainfo.resources | length == 0

    - name: Wait for VM B to be running
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        namespace: "namespace-{{ user }}"
        name: "exercise11-b"
      register: exercise11binfo
      until: " exercise11binfo.resources | length > 0 and exercise11binfo.resources[0].status.phase == 'Running'"
      retries: 60
      delay: 10
      failed_when: exercise11binfo.resources | length == 0
