- name: Fixing the exercise1
  hosts: localhost
  gather_facts: true

  vars:
    user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Check if exercise1 VM exists
      kubernetes.core.k8s_info:
        namespace: "namespace-{{ user }}"
        kind: VirtualMachine
        name: exercise1
      register: ex1vm
      failed_when: false

    - name: Stop VM exercise1 if it exists
      kubernetes.core.k8s:
        namespace: "namespace-{{ user }}"
        kind: VirtualMachine
        name: exercise1
        state: present
        definition:
          spec:
            running: false
      register: stopvm
      until: stopvm is succeeded
      retries: 60
      delay: 10
      when: ex1vm.resources | length > 0

    - name: Fixing the exercise1
      kubernetes.core.k8s:
        state: present
        template: "exercise1-fix-vm.yaml.j2"
      register: fixvm
      until: fixvm is succeeded
      retries: 60
      delay: 10
      failed_when: fixvm is failed or fixvm.failed

    - name: Wait for VM to be running
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        namespace: "namespace-{{ user }}"
        name: "exercise1"
      register: exercise1info
      until: "exercise1info.resources | length > 0 and exercise1info.resources[0].status.phase == 'Running'"
      retries: 60
      delay: 10
      failed_when: exercise1info.resources | length == 0
