- name: Grading the exercise3
  hosts: localhost
  gather_facts: true

  vars:
    user: "{{ lookup('env', 'USER') }}"

  tasks:
    - block:
        - name: Try to fetch namespaces to check connection
          kubernetes.core.k8s_info:
            api_version: v1
            kind: Namespace
          register: namespaces
          no_log: true
      rescue:
        - name: Display error message
          ansible.builtin.fail:
            msg: "You are not connected into the cluster. Please use the lab instruction to connect on the cluster using user '{{ user }}'"

    - name: Getting URL from route
      kubernetes.core.k8s_info:
        kind: Route
        namespace: "namespace-{{ user }}"
        name: exercise3
      register: routefacts

    - name: Access the URL and check for the response
      ansible.builtin.uri:
        url: "https://{{ routefacts.resources[0].spec.host }}"
        method: GET
        return_content: true
      register: urlcontent

    - name: Assert that is in the response body expected
      ansible.builtin.assert:
        that:
          - "'Hello from exercise3, you are doing a great job!' in urlcontent.content"
        success_msg: "Good job, its working as expected!"
        fail_msg: "Ops, something went wrong and you have to fix the exercise!"
