---
- name: Preparing the exercise7
  hosts: localhost
  gather_facts: true

  vars:
    user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Creating the exercise7 virtual machine
      kubernetes.core.k8s:
        state: present
        template: "exercise7-vm.yaml.j2"
      register: breakvm
      until: breakvm is succeeded
      retries: 60
      delay: 10
      failed_when: breakvm is failed or breakvm.failed

    - name: Create the VM snapshot
      kubernetes.core.k8s:
        kind: VirtualMachineSnapshot
        namespace: 'namespace-{{ user }}'
        definition:
          apiVersion: snapshot.kubevirt.io/v1alpha1
          kind: VirtualMachineSnapshot
          metadata:
            name: exercise7-snapshot
          spec:
            source:
              apiGroup: kubevirt.io
              kind: VirtualMachine
              name: exercise7

    - name: Change memory to 8GB
      kubernetes.core.k8s:
        state: present
        kind: VirtualMachine
        api_version: kubevirt.io/v1
        name: exercise7
        namespace: 'namespace-{{ user }}'
        merge_type: merge
        definition:
          spec:
            template:
              spec:
                domain:
                  memory:
                    guest: "8Gi"

    - name: Restore o snapshot
      kubernetes.core.k8s:
        kind: VirtualMachineRestore
        namespace: 'namespace-{{ user }}'
        definition:
          apiVersion: snapshot.kubevirt.io/v1alpha1
          kind: VirtualMachineRestore
          metadata:
            name: restore-exercise7-snapshot
          spec:
            target:
              apiGroup: kubevirt.io
              kind: VirtualMachine
              name: exercise7
            virtualMachineSnapshotName: exercise7-snapshot
