- name: Preparing  exercise11
  hosts: localhost
  gather_facts: true

  vars:
    user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Creating NAD
      kubernetes.core.k8s:
        state: present
        template: "exercise11-create-nad.yaml.j2"
      register: createnad
      until: createnad is succeeded
      retries: 60
      delay: 10
      failed_when: createnad is failed or createnad.failed

    - name: Creating VM A
      kubernetes.core.k8s:
        state: present
        template: "exercise11-create-vm-a.yaml.j2"
      register: createvma
      until: createvma is succeeded
      retries: 60
      delay: 10
      failed_when: createvma is failed or createvma.failed

    - name: Creating VM B
      kubernetes.core.k8s:
        state: present
        template: "exercise11-create-vm-b.yaml.j2"
      register: createvmb
      until: createvmb is succeeded
      retries: 60
      delay: 10
      failed_when: createvmb is failed or createvmb.failed
