- name: Fixing the exercise1
  hosts: localhost
  gather_facts: true

  vars:
    user: "{{ lookup('env', 'USER') }}"

  tasks:
    - block:
        - name: Try to fetch namespaces to check connection
          kubernetes.core.k8s_info:
            api_version: v1
            kind: Namespace
          register: namespaces
          no_log: true
      rescue:
        - name: Display error message
          ansible.builtin.fail:
            msg: "You are not connected into the cluster. Please use the lab instruction to connect on the cluster using user '{{ user }}'"

    - name: Set VM to stopped state
      kubernetes.core.k8s:
        namespace: "namespace-{{ user }}"
        kind: VirtualMachine
        name: exercise1
        state: present
        definition:
          spec:
            running: false
      register: stopvm
      until: stopvm is succeeded
      retries: 60
      delay: 10
      failed_when: stopvm is failed or stopvm.failed

    - name: Fixing the exercise1
      kubernetes.core.k8s:
        state: present
        template: "exercise1-fix-vm.yaml.j2"
      register: fixvm
      until: fixvm is succeeded
      retries: 60
      delay: 10
      failed_when: fixvm is failed or fixvm.failed
