- name: Fixing the exercise4
  hosts: localhost
  gather_facts: true

  vars:
    user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Get the exercise6 VM details from OpenShift Virtualization
      kubernetes.core.k8s_info:
        kind: VirtualMachine
        api_version: kubevirt.io/v1
        name: exercise6
        namespace: "namespace-{{ user }}"
      register: vm_info

    - name: Get the cloudinitdisk details
      ansible.builtin.set_fact:
        cloudinitdisk: " {{
          vm_info.resources[0].spec.template.spec.domain.devices.disks[1]
        }}"

    - name: Certify that the cloudinitdisk have no readonly attribute
      ansible.builtin.assert:
        that:
          - "'readonly' not in cloudinitdisk"
        success_msg: "Yeah Yeah Yeah, the virtual machine can be migrate to another node now!"
        fail_msg: "Ops, something went wrong and you have to fix the exercise!"
