- name: Fixing the exercise8
  hosts: localhost
  gather_facts: true

  vars:
    user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Create SSH config file with StrictHostKeyChecking no
      ansible.builtin.copy:
        dest: '/home/{{ user }}/.ssh/config'
        content: |
          Host *
            StrictHostKeyChecking no
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: '0600'

    - name: Updating the idrsa secret
      ansible.builtin.command:
        cmd: virtctl credentials add-ssh-key -f /home/{{ user }}/.ssh/id_rsa --user lab-user --force exercise8

    - name: Testing the ssh access
      ansible.builtin.command:
        cmd: virtctl ssh lab-user@exercise8
      no_log: true
      register: testssh
      until: testssh.rc == 0
      retries: 60
      delay: 10
