- name: Fixing the exercise6
  hosts: localhost
  gather_facts: true

  vars:
    user: "{{ lookup('env', 'USER') }}"

  tasks:
    - block:
        - name: Try to fetch namespaces to check connection
          kubernetes.core.k8s_info:
            api_version: v1
            kind: Namespace
          register: namespaces
          no_log: true
      rescue:
        - name: Display error message
          ansible.builtin.fail:
            msg: "You are not connected into the cluster. Please use the lab instruction to connect on the cluster using user '{{ user }}'"

    - name: Set VM to stopped state
      kubernetes.core.k8s:
        namespace: "namespace-{{ user }}"
        kind: VirtualMachine
        name: exercise6
        state: present
        definition:
          spec:
            running: false
      register: stopvm
      until: stopvm is succeeded
      retries: 60
      delay: 10
      failed_when: stopvm is failed or stopvm.failed

    - name: Fixing exercise6 virtual machine
      kubernetes.core.k8s:
        state: present
        template: "exercise6-fix-vm.yaml.j2"
      register: exercise6vm
      until: exercise6vm is succeeded
      retries: 60
      delay: 10
      failed_when: exercise6vm is failed or exercise6vm.failed

    - name: Set VM to start state
      kubernetes.core.k8s:
        namespace: "namespace-{{ user }}"
        kind: VirtualMachine
        name: exercise6
        state: present
        definition:
          spec:
            running: true
      register: startvm
      until: startvm is succeeded
      retries: 60
      delay: 10
      failed_when: startvm is failed or startvm.failed
