- name: Preparing exercise3
  hosts: localhost
  gather_facts: no

  vars:
    user: "{{ lookup('env', 'USER') }}"

  tasks:
        
    - name: Creating VM exercise3
      kubernetes.core.k8s:
        state: present
        template: "exercise3-create-vm.yaml.j2"
      register: createvm
      until: createvm is succeeded
      retries: 60
      delay: 10
      failed_when: createvm is failed or createvm.failed