- name: Grading the exercise1
  hosts: localhost
  gather_facts: true

  vars:
    user: "{{ lookup('env', 'USER') }}"

  tasks:
    - block:
        - name: Try to fetch namespaces to check connection
          kubernetes.core.k8s_info:
            api_version: v1
            kind: Namespace
          register: namespaces
          no_log: true
      rescue:
        - name: Display error message
          ansible.builtin.fail:
            msg: "You are not connected into the cluster. Please use the lab instruction to connect on the cluster using user '{{ user }}'"

    - name: Get Virtual Machine status
      kubernetes.core.k8s_info:
        kind: VirtualMachine
        namespace: "namespace-{{ user }}"
        name: exercise1
      register: exercise1_info

    - name: Check if VM is running
      ansible.builtin.debug:
        msg: "The Virtual Machine is running."
      when: exercise1_info.resources[0].status.printableStatus == "Running"

    - name: Check if VM is not running
      ansible.builtin.debug:
        msg: "The Virtual Machine is NOT running."
      when: exercise1_info.resources[0].status.printableStatus != "Running"
