- name: Cleaning the exercise4
  hosts: localhost
  gather_facts: true

  vars:
    user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Removing exercise6 virtual machine
      kubernetes.core.k8s:
        state: absent
        template: "exercise6-create-vm.yaml.j2"
      register: exercise6vm
      until: exercise6vm is succeeded
      retries: 60
      delay: 10
      failed_when: exercise6vm is failed or exercise6vm.failed
