- name: Cleaning the exercise3
  hosts: localhost
  gather_facts: true

  vars:
    user: "{{ lookup('env', 'USER') }}"

  tasks:
    - block:
        - name: Try to fetch namespaces to check connection
          kubernetes.core.k8s_info:
            api_version: v1
            kind: Namespace
          register: namespaces
          no_log: true
      rescue:
        - name: Display error message
          ansible.builtin.fail:
            msg: "You are not connected into the cluster. Please use the lab instruction to connect on the cluster using user '{{ user }}'"

    - name: Removing exercise3 virtual machine
      kubernetes.core.k8s:
        state: absent
        template: "exercise3-vm.yaml.j2"
      register: exerciseXvm
      until: exerciseXvm is succeeded
      retries: 60
      delay: 10
      failed_when: exerciseXvm is failed or exerciseXvm.failed

    - name: Removing exercise3 service
      kubernetes.core.k8s:
        state: absent
        template: "exercise3-service.yaml.j2"
      register: exerciseXsvc
      until: exerciseXsvc is succeeded
      retries: 60
      delay: 10
      failed_when: exerciseXsvc is failed or exerciseXsvc.failed

    - name: Removing exercise3 route
      kubernetes.core.k8s:
        state: absent
        template: "exercise3-break-route.yaml.j2"
      register: exerciseXroute
      until: exerciseXroute is succeeded
      retries: 60
      delay: 10
      failed_when: exerciseXroute is failed or exerciseXroute.failed

    - name: Removing curl image pod for tests
      kubernetes.core.k8s:
        state: absent
        template: "curl-pod.yaml.j2"
      register: exerciseXcurlpod
      until: exerciseXcurlpod is succeeded
      retries: 60
      delay: 10
      failed_when: exerciseXcurlpod is failed or exerciseXcurlpod.failed
