- name: Preparing the exercise5
  hosts: localhost
  gather_facts: true

  vars:
    user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Creating virtual machine
      kubernetes.core.k8s:
        state: present
        template: "exercise5-create-vm.yaml.j2"
      register: exercise5vm
      until: exercise5vm is succeeded
      retries: 5
      delay: 10
      failed_when: exercise5vm is failed or exercise5vm.failed

    - name: Wait for VM to be running
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        namespace: "namespace-{{ user }}"
        name: "exercise5"
      register: exercise5info
      until: "exercise5info.resources | length > 0 and exercise5info.resources[0].status.phase == 'Running'"
      retries: 60
      delay: 10
      failed_when: exercise5info.resources | length == 0

    - name: Add data volume to virtual machine
      kubernetes.core.k8s:
        state: present
        template: "exercise5-breakdatavol.yaml.j2"
      register: exercise5datavol
      until: exercise5datavol is succeeded
      retries: 5
      delay: 10
      failed_when: exercise5datavol is failed or exercise5datavol.failed

    - name: Add data disk 1 to virtual machine
      ansible.builtin.command: virtctl addvolume exercise5 --volume-name=exercise5-vol-data1 --persist
      register: exercise5fixdatadisk1