- name: Grading the exercise8
  hosts: localhost
  gather_facts: true

  vars:
    user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Testing the ssh access
      ansible.builtin.command:
        cmd: virtctl ssh lab-user@exercise8
      ignore_errors: true
      no_log: true
      register: testssh

    - name: Check if snapshot has not been restored
      ansible.builtin.fail:
        msg: "Ooops, SSH is not working"
      when: testssh.rc != 0