- name: Preparing the exercise4
  hosts: localhost
  gather_facts: true

  vars:
    user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Get user SSH key
      ansible.builtin.slurp:
        src: "/home/{{ user }}/.ssh/id_rsa.pub"
      register: usersshkey

    - name: Create the idrsa secret
      kubernetes.core.k8s:
        state: present
        template: "exercise4-secret.yaml.j2"
      register: secretidrsa
      until: secretidrsa is succeeded
      retries: 60
      delay: 10
      failed_when: secretidrsa is failed or secretidrsa.failed

    - name: Creating exercise4 virtual machine
      kubernetes.core.k8s:
        state: present
        template: "exercise4-break-vm.yaml.j2"
      register: exercise4vm
      until: exercise4vm is succeeded
      retries: 60
      delay: 10
      failed_when: exercise4vm is failed or exercise4vm.failed

    - name: Wait for VM to be running
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        namespace: "namespace-{{ user }}"
        name: "exercise4"
      register: exercise4info
      until: "exercise4info.resources | length > 0 and exercise4info.resources[0].status.phase == 'Running'"
      retries: 60
      delay: 10
      failed_when: exercise4info.resources | length == 0

    - name: Sleeping for 2 minutes to generate load
      ansible.builtin.pause:
        minutes: 2
