- name: Fixing the exercise9
  hosts: localhost
  gather_facts: true

  vars:
    user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Patch the Virtual Machine exercise9 runStrategy to Manual
      kubernetes.core.k8s:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: exercise9
        namespace: "namespace-{{ user }}"
        patch:
          spec:
            runStrategy: Manual
        state: patched
